import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
    if (!LOVABLE_API_KEY) {
      throw new Error('LOVABLE_API_KEY is not configured');
    }

    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    const { 
      ownerFirstName, 
      propertyName, 
      promptTemplate,
      holidayName // Optional: for better context
    } = await req.json();

    console.log('Generating holiday image for:', { ownerFirstName, propertyName, holidayName });

    // Build the personalized prompt from the template
    let personalizedPrompt = (promptTemplate || '')
      .replace(/{owner_first_name}/g, ownerFirstName || 'Friend')
      .replace(/{owner_name}/g, ownerFirstName || 'Friend')
      .replace(/{property_name}/g, propertyName || 'your property');

    // If no prompt template, create a generic one based on holiday name
    if (!personalizedPrompt || personalizedPrompt.trim().length < 20) {
      personalizedPrompt = `Create a beautiful ${holidayName || 'holiday'} greeting card image. 
      A warm, inviting scene with elegant text saying "Happy ${holidayName || 'Holidays'}, ${ownerFirstName || 'Friend'}!" prominently displayed.
      Style: High quality, warm and inviting, perfect for a greeting card.`;
    }

    // Ensure the prompt includes the owner name for personalization
    if (!personalizedPrompt.includes(ownerFirstName) && ownerFirstName) {
      personalizedPrompt += `\n\nIMPORTANT: The image MUST include text greeting "${ownerFirstName}" prominently.`;
    }

    console.log('Using prompt:', personalizedPrompt.substring(0, 200) + '...');

    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash-image-preview",
        messages: [
          {
            role: "user",
            content: personalizedPrompt
          }
        ],
        modalities: ["image", "text"]
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('AI gateway error:', response.status, errorText);
      
      if (response.status === 429) {
        throw new Error('Rate limit exceeded. Please try again in a moment.');
      }
      if (response.status === 402) {
        throw new Error('AI credits exhausted. Please add funds to continue.');
      }
      throw new Error(`AI gateway error: ${response.status}`);
    }

    const data = await response.json();
    console.log('AI response received');

    // Extract the generated image
    const imageData = data.choices?.[0]?.message?.images?.[0]?.image_url?.url;
    
    if (!imageData) {
      console.error('No image in response:', JSON.stringify(data).substring(0, 500));
      throw new Error('No image was generated by the AI');
    }

    // The image is base64 encoded, save it to storage
    const base64Data = imageData.replace(/^data:image\/\w+;base64,/, '');
    const imageBuffer = Uint8Array.from(atob(base64Data), c => c.charCodeAt(0));

    // Generate unique filename with holiday context
    const timestamp = Date.now();
    const holidaySlug = (holidayName || 'holiday').replace(/\s+/g, '-').toLowerCase();
    const ownerSlug = (ownerFirstName || 'owner').replace(/\s+/g, '_');
    const fileName = `${timestamp}-${holidaySlug}-${ownerSlug}.png`;
    const filePath = `generated/${fileName}`;

    // Upload to storage
    const { error: uploadError } = await supabase.storage
      .from('holiday-images')
      .upload(filePath, imageBuffer, {
        contentType: 'image/png',
        upsert: true
      });

    if (uploadError) {
      console.error('Upload error:', uploadError);
      throw new Error(`Failed to save image: ${uploadError.message}`);
    }

    // Get public URL
    const { data: { publicUrl } } = supabase.storage
      .from('holiday-images')
      .getPublicUrl(filePath);

    console.log('Image saved successfully:', publicUrl);

    return new Response(
      JSON.stringify({ 
        success: true, 
        imageUrl: publicUrl
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('Error generating holiday image:', error);
    return new Response(
      JSON.stringify({ 
        error: error instanceof Error ? error.message : 'Unknown error',
        success: false 
      }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
