-- Continue importing property data for remaining properties

-- Villa 3 (2580 Old Roswell Rd, House #A, Smyrna) - Old Rowsell
UPDATE onboarding_tasks SET field_value = 'Old Rowsell' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%2580 Old Roswell%') AND title = 'Brand Name';
UPDATE onboarding_tasks SET field_value = 'Townhouse' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%2580 Old Roswell%') AND title = 'Property Type Detail';
UPDATE onboarding_tasks SET field_value = '2' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%2580 Old Roswell%') AND title = 'Stories';
UPDATE onboarding_tasks SET field_value = 'driveway parking 2 cars' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%2580 Old Roswell%') AND title = 'Parking Type';
UPDATE onboarding_tasks SET field_value = '2' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%2580 Old Roswell%') AND title = 'Parking Capacity';
UPDATE onboarding_tasks SET field_value = 'YES' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%2580 Old Roswell%') AND title = 'Fenced Yard';
UPDATE onboarding_tasks SET field_value = '2' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%2580 Old Roswell%') AND title = 'Bedrooms';
UPDATE onboarding_tasks SET field_value = '2.5' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%2580 Old Roswell%') AND title = 'Bathrooms';
UPDATE onboarding_tasks SET field_value = '1372' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%2580 Old Roswell%') AND title = 'Square Footage';
UPDATE onboarding_tasks SET field_value = 'Yes' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%2580 Old Roswell%') AND title = 'Pets Allowed';
UPDATE onboarding_tasks SET field_value = '2 dogs max, up to 40 lbs' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%2580 Old Roswell%') AND title = 'Pet Rules';
UPDATE onboarding_tasks SET field_value = '2' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%2580 Old Roswell%') AND title = 'Maximum Number of Pets';
UPDATE onboarding_tasks SET field_value = '40' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%2580 Old Roswell%') AND title = 'Maximum Pet Weight (lbs)';
UPDATE onboarding_tasks SET field_value = '$5,640.00' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%2580 Old Roswell%') AND title = 'Monthly Rent';
UPDATE onboarding_tasks SET field_value = '$188.00' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%2580 Old Roswell%') AND title = 'Nightly Rate';
UPDATE onboarding_tasks SET field_value = '$1,500.00' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%2580 Old Roswell%') AND title = 'Security Deposit';
UPDATE onboarding_tasks SET field_value = '$500.00' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%2580 Old Roswell%') AND title = 'Utility Cap';
UPDATE onboarding_tasks SET field_value = '$400.00' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%2580 Old Roswell%') AND title = 'Cleaning Fee';
UPDATE onboarding_tasks SET field_value = '$350.00' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%2580 Old Roswell%') AND title = 'Admin Fee';
UPDATE onboarding_tasks SET field_value = '$300.00' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%2580 Old Roswell%') AND title = 'Pet Fee';
UPDATE onboarding_tasks SET field_value = '$150.00' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%2580 Old Roswell%') AND title = 'Monthly Pet Rent';
UPDATE onboarding_tasks SET field_value = '$120' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%2580 Old Roswell%') AND title = 'Monthly Cleaning Fee';
UPDATE onboarding_tasks SET field_value = 'month to month' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%2580 Old Roswell%') AND title = 'Lease Term';
UPDATE onboarding_tasks SET field_value = '30 days' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%2580 Old Roswell%') AND title = 'Notice to Vacate';
UPDATE onboarding_tasks SET field_value = 'anja@peachhausgroup.com' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%2580 Old Roswell%') AND title = 'Contact Email';
UPDATE onboarding_tasks SET field_value = 'https://oldroswell.peachhausgroup.com/' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%2580 Old Roswell%') AND title = 'Direct Booking Website';
UPDATE onboarding_tasks SET field_value = 'Smyrna Elementary' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%2580 Old Roswell%') AND title = 'School District';
UPDATE onboarding_tasks SET field_value = 'Smyrna Elementary' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%2580 Old Roswell%') AND title = 'Elementary School';
UPDATE onboarding_tasks SET field_value = 'Campbell Middle' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%2580 Old Roswell%') AND title = 'Middle School';
UPDATE onboarding_tasks SET field_value = 'Campbell HS' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%2580 Old Roswell%') AND title = 'High School';

-- Villa 4 (3069 Rita Way, Smyrna) - The Homerun Hideaway
UPDATE onboarding_tasks SET field_value = 'The Homerun Hideaway' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3069 Rita%') AND title = 'Brand Name';
UPDATE onboarding_tasks SET field_value = 'SFH' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3069 Rita%') AND title = 'Property Type Detail';
UPDATE onboarding_tasks SET field_value = '1 (ranch style)' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3069 Rita%') AND title = 'Stories';
UPDATE onboarding_tasks SET field_value = '1 carport, driveway 2 cars' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3069 Rita%') AND title = 'Parking Type';
UPDATE onboarding_tasks SET field_value = '2' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3069 Rita%') AND title = 'Parking Capacity';
UPDATE onboarding_tasks SET field_value = 'YES' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3069 Rita%') AND title = 'Fenced Yard';
UPDATE onboarding_tasks SET field_value = '3' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3069 Rita%') AND title = 'Bedrooms';
UPDATE onboarding_tasks SET field_value = '2' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3069 Rita%') AND title = 'Bathrooms';
UPDATE onboarding_tasks SET field_value = '1050' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3069 Rita%') AND title = 'Square Footage';
UPDATE onboarding_tasks SET field_value = 'Yes' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3069 Rita%') AND title = 'Pets Allowed';
UPDATE onboarding_tasks SET field_value = '2 dogs max, up to 40 lbs' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3069 Rita%') AND title = 'Pet Rules';
UPDATE onboarding_tasks SET field_value = '2' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3069 Rita%') AND title = 'Maximum Number of Pets';
UPDATE onboarding_tasks SET field_value = '40' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3069 Rita%') AND title = 'Maximum Pet Weight (lbs)';
UPDATE onboarding_tasks SET field_value = '$6,270.00' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3069 Rita%') AND title = 'Monthly Rent';
UPDATE onboarding_tasks SET field_value = '$209.00' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3069 Rita%') AND title = 'Nightly Rate';
UPDATE onboarding_tasks SET field_value = '$1,500.00' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3069 Rita%') AND title = 'Security Deposit';
UPDATE onboarding_tasks SET field_value = '$500.00' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3069 Rita%') AND title = 'Utility Cap';
UPDATE onboarding_tasks SET field_value = '$450.00' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3069 Rita%') AND title = 'Cleaning Fee';
UPDATE onboarding_tasks SET field_value = '$350.00' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3069 Rita%') AND title = 'Admin Fee';
UPDATE onboarding_tasks SET field_value = '$300.00' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3069 Rita%') AND title = 'Pet Fee';
UPDATE onboarding_tasks SET field_value = '$150.00' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3069 Rita%') AND title = 'Monthly Pet Rent';
UPDATE onboarding_tasks SET field_value = '$150' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3069 Rita%') AND title = 'Monthly Cleaning Fee';
UPDATE onboarding_tasks SET field_value = 'month to month' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3069 Rita%') AND title = 'Lease Term';
UPDATE onboarding_tasks SET field_value = '30 days' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3069 Rita%') AND title = 'Notice to Vacate';
UPDATE onboarding_tasks SET field_value = 'anja@peachhausgroup.com' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3069 Rita%') AND title = 'Contact Email';
UPDATE onboarding_tasks SET field_value = 'https://ritaway.peachhausgroup.com' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3069 Rita%') AND title = 'Direct Booking Website';
UPDATE onboarding_tasks SET field_value = 'Smyrna Elementary' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3069 Rita%') AND title = 'School District';
UPDATE onboarding_tasks SET field_value = 'Smyrna Elementary' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3069 Rita%') AND title = 'Elementary School';
UPDATE onboarding_tasks SET field_value = 'Campbell Middle' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3069 Rita%') AND title = 'Middle School';
UPDATE onboarding_tasks SET field_value = 'Campbell HS' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3069 Rita%') AND title = 'High School';

-- Villa 5 (3155 Duvall Pl Kennesaw) - Scandi Chic
UPDATE onboarding_tasks SET field_value = 'Scandi Chic' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3155 Duvall%') AND title = 'Brand Name';
UPDATE onboarding_tasks SET field_value = 'Townhouse' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3155 Duvall%') AND title = 'Property Type Detail';
UPDATE onboarding_tasks SET field_value = '2' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3155 Duvall%') AND title = 'Stories';
UPDATE onboarding_tasks SET field_value = 'driveway 3 cars' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3155 Duvall%') AND title = 'Parking Type';
UPDATE onboarding_tasks SET field_value = '3' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3155 Duvall%') AND title = 'Parking Capacity';
UPDATE onboarding_tasks SET field_value = 'NO' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3155 Duvall%') AND title = 'Fenced Yard';
UPDATE onboarding_tasks SET field_value = '2' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3155 Duvall%') AND title = 'Bedrooms';
UPDATE onboarding_tasks SET field_value = '2' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3155 Duvall%') AND title = 'Bathrooms';
UPDATE onboarding_tasks SET field_value = '1600' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3155 Duvall%') AND title = 'Square Footage';
UPDATE onboarding_tasks SET field_value = 'Yes' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3155 Duvall%') AND title = 'Pets Allowed';
UPDATE onboarding_tasks SET field_value = '2 dogs max, up to 40 lbs' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3155 Duvall%') AND title = 'Pet Rules';
UPDATE onboarding_tasks SET field_value = '2' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3155 Duvall%') AND title = 'Maximum Number of Pets';
UPDATE onboarding_tasks SET field_value = '40' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3155 Duvall%') AND title = 'Maximum Pet Weight (lbs)';
UPDATE onboarding_tasks SET field_value = '$5,670.00' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3155 Duvall%') AND title = 'Monthly Rent';
UPDATE onboarding_tasks SET field_value = '$189.00' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3155 Duvall%') AND title = 'Nightly Rate';
UPDATE onboarding_tasks SET field_value = '$1,500.00' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3155 Duvall%') AND title = 'Security Deposit';
UPDATE onboarding_tasks SET field_value = '$500.00' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3155 Duvall%') AND title = 'Utility Cap';
UPDATE onboarding_tasks SET field_value = '$400.00' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3155 Duvall%') AND title = 'Cleaning Fee';
UPDATE onboarding_tasks SET field_value = '$350.00' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3155 Duvall%') AND title = 'Admin Fee';
UPDATE onboarding_tasks SET field_value = '$300.00' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3155 Duvall%') AND title = 'Pet Fee';
UPDATE onboarding_tasks SET field_value = '$150.00' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3155 Duvall%') AND title = 'Monthly Pet Rent';
UPDATE onboarding_tasks SET field_value = '$120' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3155 Duvall%') AND title = 'Monthly Cleaning Fee';
UPDATE onboarding_tasks SET field_value = 'month to month' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3155 Duvall%') AND title = 'Lease Term';
UPDATE onboarding_tasks SET field_value = '30 days' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3155 Duvall%') AND title = 'Notice to Vacate';
UPDATE onboarding_tasks SET field_value = 'anja@peachhausgroup.com' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3155 Duvall%') AND title = 'Contact Email';
UPDATE onboarding_tasks SET field_value = 'http://scandi-chic.peachhausgroup.com/' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3155 Duvall%') AND title = 'Direct Booking Website';
UPDATE onboarding_tasks SET field_value = 'Big Shanty Elementary' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3155 Duvall%') AND title = 'School District';
UPDATE onboarding_tasks SET field_value = 'Big Shanty Elementary' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3155 Duvall%') AND title = 'Elementary School';
UPDATE onboarding_tasks SET field_value = 'Palmer Middle School' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3155 Duvall%') AND title = 'Middle School';
UPDATE onboarding_tasks SET field_value = 'North Cobb HS' WHERE project_id IN (SELECT id FROM onboarding_projects WHERE property_address LIKE '%3155 Duvall%') AND title = 'High School';