-- Add reply_transcript column to voicemail_messages
ALTER TABLE public.voicemail_messages 
ADD COLUMN IF NOT EXISTS reply_transcript TEXT;

-- Add comment for documentation
COMMENT ON COLUMN public.voicemail_messages.reply_transcript IS 'Transcript of the voice reply from recipient, generated by OpenAI Whisper';